Billeterie/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from debug_toolbar.toolbar import debug_toolbar_urls
from Billeterie import settings

from store.views import about, index, legal_notice

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('legal/', legal_notice, name='legal-notice'),
    path('admin/', admin.site.urls),
    path('account/', include('accounts.urls')),
    path('store/', include('store.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + debug_toolbar_urls()

store/urls.py
from django.urls import path
from store.views import offer_detail, add_to_cart, cart, delete_cart, create_checkout_session, checkout_success, update_quantities, all_offers

app_name = "store"

urlpatterns = [
    path('cart/', cart, name="cart"),
    path('cart/update_quantities', update_quantities, name="update-quantities"),
    path('cart/delete/', delete_cart, name="delete-cart"),
    path('cart/create-checkout-session', create_checkout_session, name="create-checkout-session"),
    path('cart/success', checkout_success, name="checkout-success"),
    path('offers/', all_offers, name="all-offers"),
    path('offers/<str:slug>', offer_detail, name="offer"),
    path('offers/<str:slug>/add-to-cart', add_to_cart, name="add-to-cart"),
]

store/models.py
import secrets
import qrcode
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.text import slugify

from Billeterie.settings import AUTH_USER_MODEL, MEDIA_QRCODE

class Offer(models.Model):
    """"Represents an offer"""
    offer_name = models.CharField(max_length=100)
    offer_slug = models.SlugField(max_length=100, blank=True)
    offer_price = models.FloatField(default=0.0)
    offer_numberOfPerson = models.IntegerField(default=0)
    offer_stock = models.IntegerField(default=0)
    offer_description = models.TextField(blank=True)

    def __str__(self):
        return f"{self.offer_name} ({self.offer_stock})"

    def get_absolute_url(self):
        return reverse("store:offer", kwargs={"slug": self.offer_slug})

    def save(self, *args, **kwargs):
        if not self.offer_slug:
            self.offer_slug = slugify(self.offer_name)
        return super().save(*args, **kwargs)
    
class Order(models.Model):
    """"Represents an order containing offer"""
    user = models.ForeignKey(AUTH_USER_MODEL, on_delete=models.CASCADE)
    offer = models.ForeignKey(Offer, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField(blank=True, null=True)
    generated_key = models.CharField(max_length=255, default="")
    generated_qr_code = models.CharField(max_length=255, default="")

    def __str__(self):
        return f"{self.offer.offer_name} ({self.quantity})"

    def generate_qr_code(self):
        """Generate a qr code based on the two generated key"""
        qr_data = f"User: {self.user.generated_key} order: {self.generated_key}"
        image = qrcode.make(qr_data)
        file_name = f"qr_code-{self.generated_key}" + ".png"
        image.save(MEDIA_QRCODE / file_name)
        self.generated_qr_code = "../../media/qr_codes/" + file_name
        self.save()

    def decrease_offer_quantity(self):
        """Allows to decrease quantity of an offer in the cart"""
        new_quantity = self.offer.offer_stock - self.quantity
        self.offer.offer_stock = new_quantity
        self.offer.save()
    
class Cart(models.Model):
    """"Represents cart"""
    user = models.OneToOneField(AUTH_USER_MODEL, on_delete=models.CASCADE)
    orders = models.ManyToManyField(Order)
    ordered = models.BooleanField(default=False)
    ordered_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.user.email or "Unknown"

    def validate_cart(self, *args, **kwargs):
        """Validate cart when purchasing"""
        for order in self.orders.all():
            order.ordered = True
            order.ordered_date = timezone.now()
            order.generated_key = secrets.token_hex(16)
            order.decrease_offer_quantity()
            order.save()
            order.generate_qr_code()
            self.orders.remove(order)
        
        self.delete()
        
    def delete(self, *args, **kwargs):
        self.orders.clear()
        super().delete(*args, **kwargs)

store/forms.py
from django import forms

from store.models import Order

class OrderForm(forms.ModelForm):
    quantity = forms.ChoiceField(choices=[(i, i) for i in range(1, 11)])
    delete = forms.BooleanField(initial=False, required=False, label="Supprimer")
    
    class Meta:
        model = Order
        fields = ["quantity"]
        
    def save(self, *args, **kwargs):
        if self.cleaned_data["delete"]:
            self.instance.delete()
            if self.instance.user.cart.orders.count() == 0:
                self.instance.user.cart.delete()
            return True
        
        return super().save(*args, **kwargs)

store/views.py
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse

from accounts.models import Customer
from store.forms import OrderForm
from store.models import Offer, Order

def index(request):
    offers = Offer.objects.all()
    return render(request, 'store/index.html', context={"offers": offers})

def about(request):
    return render(request, 'store/about.html')

def legal_notice(request):
    return render(request, 'store/legal.html')

def all_offers(request):
    offers = Offer.objects.all()
    return render(request, 'store/offers.html', context={"offers": offers})

def offer_detail(request, slug):
    offer = get_object_or_404(Offer, offer_slug=slug)
    return render(request, 'store/detail.html', context={"offer": offer})

@login_required
def cart(request):
    orders = Order.objects.filter(user=request.user, ordered=False)
    if orders.count() == 0:
        return redirect('index')
    OrderFormSet = modelformset_factory(Order, form=OrderForm, extra=0)
    formset = OrderFormSet(queryset=orders)
    
    return render(request, 'store/cart.html', context={"forms": formset})

def update_quantities(request):
    OrderFormSet = modelformset_factory(Order, form=OrderForm, extra=0)
    formset = OrderFormSet(request.POST, queryset=Order.objects.filter(user=request.user))
    if formset.is_valid():
        formset.save()
        
    return redirect('store:cart')

def add_to_cart(request, slug):
    user: Customer = request.user
    user.add_to_cart(slug=slug)
        
    return redirect(reverse("store:offer", kwargs={"slug": slug}))

def delete_cart(request):
    if cart := request.user.cart:
        cart.delete()
        
    return redirect('index')

def create_checkout_session(request):
    cart = request.user.cart
    orders = cart.orders.all()
    items_in_cart = [{"price": order.offer.offer_price,
                        "quantity": order.quantity,
                        "name": order.offer.offer_name} for order in orders]
    total = 0
    for order in orders:
        total += order.offer.offer_price * order.quantity

    return render(request, 'store/checkoutSession.html', context={"items": items_in_cart, "total": total})

def checkout_success(request):
    request.user.cart.validate_cart()
    return render(request, 'store/success.html')

store/templates/store/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
        <div class="container">
            <h1>A propos</h1>
            <p>Ce site a été réalisé dans le cadre d'un projet étudiant afin de valider le diplôme.</p>
            <p>Le but de ce projet est de réalisé un site de type e-commerce dans le cadre des JO de Paris 2024.</p>
            <p>Ce n'est donc pas un vrai site officiel pour les JO de Paris 2024.</p>
            <p>La fonctionnalité de paiement n'est par ailleurs pas disponible.</p>
        </div>
    </main>
{% endblock %}

store/templates/store/cart.html
{% extends 'base.html' %}

{% block content %}
<div id="cart-container" class="container">
    <form method="POST" action="{% url 'store:update-quantities' %}">
        {% csrf_token %}
        {{ forms.management_form }}
        {% for form in forms %} 
                <div>
                    <h3>{{ form.instance.offer.offer_name }}</h3>
                    <p>{{ form.instance.offer.offer_description }}</p>
                    {{ form.as_p }}
                </div>
        {% endfor %}
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary button-width">Mettre à jour les quantités</button>
    </form>

    {% comment %} later it will redirect to stripe {% endcomment %}
    <form action="{% url 'store:create-checkout-session' %}" method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-lg btn-block btn-outline-primary button-width">Procéder au paiement</button>
    </form>
    <a href="{% url 'store:delete-cart' %}" class="btn btn-lg btn-block btn-outline-secondary button-width">Supprimer le panier</a>
</div>

{% endblock %}

store/templates/store/checkoutSession.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div id="checkout-container" class="container">
        <h1>Paiement</h1>
        <h3>Votre panier contient:</h3>
        <ul class="list-group">
            {% for item in items %}
            <li>{{ item.name }}: {{ item.quantity }}</li>
            {% endfor %}
        </ul>
        <h5>Pour un total de: {{ total }}€</h5>
        <div id="checkout-buttons">
            <a href="{% url 'store:checkout-success' %}" class="btn btn-lg btn-block btn-outline-primary button-width">Valider le paiement</a>
            <a href="{% url 'store:cart' %}" class="btn btn-lg btn-block btn-outline-secondary button-width">Retour au panier</a>
        </div>

    </div>
</main>

{% endblock %}

store/templates/store/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
        <div id="offer-container" class="container">
            <h2>{{ offer.offer_name }}</h2>
            <h3>{{ offer.offer_price }}€</h3>
            <p>{{ offer.offer_description }}</p>
            <p>{{ offer.offer_stock }} en stock</p>
            
            {% if user.is_authenticated %}
            <p>
                <a href="{% url 'store:add-to-cart' offer.offer_slug %}" class="btn btn-lg btn-block btn-outline-primary">Ajouter au panier</a>
            </p>
            {% endif %}
        </div>
    </main>

{% endblock %}

store/templates/store/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
        {% if messages %}
            <div id="messages">
                {% for message in messages %}
                <div class="message alert alert-info" role="alert">
                    <button class="close-btn" onclick="this.parentElement.remove();">&times;</button>
                    {{ message }}
                </div>
                {% endfor %}
            </div>
        {% endif %}
        <div class="container col-xxl-8 px-4 py-5">
            <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
                <div class="col-10 col-sm-8 col-lg-6">
                    <img src="{% static 'img/paris.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="La ville des Paris" width="700" height="500" loading="lazy">
                </div>
                <div class="col-lg-6">
                    <h1 class="display-5 fw-bold lh-1 mb-3">Paris acceuille les Jeux olympiques 2024!</h1>
                    <p class="lead">La ville Lumière a la chance et l'honneur d'acceuillir les Jeux olympiques et paralympiques de 2024. Vous pourrez trouver sur ce site différentes offres vous permettant d'accèder aux épreuves.</p>
                    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                        <a href="{% url 'store:all-offers' %}" class="btn btn-primary btn-lg px-4 me-md-2">Accéder aux offres</a>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <h2>Qu'est ce que les Jeux olympiques ?</h2>
            <p>
                Les Jeux olympiques d'été c'est avant tout une compétition sportive rassemblant les payx du monde entier.
                Ces jeux se déroulent tous les 4 ans et le pays hôte change pour chaque édition.
                La création du format que l'on connait de ces jeux remontent en 1896 à Athènes mais leur origine est bien plus ancienne : la Grèce antique.
            </p>
        </div>
        <div class="container">
            <h2>Ce qui vous attend pour cette édition:</h2>
            <ul>
                <li>Des épreuves tous les jours pendant une 15 jours</li>
                <li>Des animations dans divers lieux</li>
                <li>Des épreuves se déroulant sur tout le territoire français</li>
            </ul>
        </div>
        <div class="container">
            <h2>Quelles épreuves pourrez vous retrouver ?</h2>
            <div class="d-flex justify-content-between">
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/volleyball.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
                        <div class="card-body">
                            <h5 class="card-title">Volley-ball</h5>
                            <p class="card-text">Sport collectif qui oppose 2 équipes de 6 personnes. Ces équipes sont séparés par un filet et un match peut durer de 1h à 1h30.</p>
                        </div>
                </div>
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/escrime.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
                    <div class="card-body">
                        <h5 class="card-title">L'escrime</h5>
                        <p class="card-text">Sport de combat qui oppose 2 athlètes devant effectuer des touches à l'aide d'un fleuret. Le but étant d'effectuer 15 touches pour l'emporter.</p>
                    </div>
                </div>
                <div class="card" style="width: 18rem;">
                    <img src="{% static 'img/athletisme.jpg' %}" class="d-block mx-lg-auto img-fluid" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
                    <div class="card-body">
                        <h5 class="card-title">L'athlétisme</h5>
                        <p class="card-text">Sport incontournable des JO, l'athlétisme comprend en réalité un ensemble d'épreuves sportives telles que le saut, la course...</p>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

store/templates/store/legal.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
        <div class="container">
            <h1>Mentions légales</h1>
            <p>Ce site a été réalisé par Fleur Dambreville dans le cadre d'un projet étudiant.</p>
            <p>La fonctionnalité de paiement n'étant pas disponible, les données renseignées par l'utilisateur ne seront pas utilisées à des fins commerciales.</p>
            <p>Ces données sont conservées uniquement pour de l'affichage et pour vérifier que l'utilisateur puisse les modifier.</p>
            <p>Pour toutes questions vous pouvez me contacter à l'adresse suivante : fleur.dambreville@gmail.com</p>
        </div>
    </main>
{% endblock %}

store/templates/store/offers.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main>
        <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
            <h1 class="display-4">Les offres</h1>
            <p class="lead">Les différentes offres que nous vous proposons donnent vous permettent d'accèder à l'évenement. Attention le nombre de personne est différent pour chaque offre.</p>
        </div>
        <div class="container">
            <div class="card-deck mb-3 text-center">
                {% for offer in offers %}
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ offer.offer_name }}</h4>
                    </div>
                    <div class="card-body">
                        <h1 class="card-title pricing-card-title">{{ offer.offer_price }}<small class="text-muted">€</small></h1>
                        <p>{{ offer.offer_description }}</p>
                        <a href="{{ offer.get_absolute_url }}" class="btn btn-lg btn-block btn-outline-primary">Voir l'offre</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </main>

{% endblock %}

store/templates/store/succes.html
{% extends 'base.html' %}

{% block content %}

    <h1>Paiement accepté!</h1>
    <p>Un QR Code va vous être envoyé (ou retrouver le sur votre espace)</p>

{% endblock %}

store/templates/store/success.html
{% extends 'base.html' %}

{% block content %}
<main>
    <div class="container">
        <h1>Paiement accepté!</h1>
        <p>Retrouver votre QR code dans votre profil</p>
    </div>
</main>

{% endblock %}